dental_clinic/dental_clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


def debug_function(request):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    users = User.objects.all()
    print(users)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/users/', include('users.urls')),
    path('api/appointments/', include('appointments.urls')),
    path('api/imaging_center/', include('imaging_center.urls')),
    path('api/donation/', include('donation.urls')),
    path('api/services/', include('services.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("debug/", debug_function, name="debug_function")
]

dental_clinic/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import (PatientProfileListCreateView,
                    DentistProfileListCreateView,
                    update_geocode,
                    create_user_from_form,
                    register_patient,
                    register_dentist,
                    register_technician,
                    FormLoginView,
                    patient_dashboard,
                    dentist_dashboard,
                    upload_image,
                    register_patient_form,
                    login_user,
                    CurrentUserProfileView,
                    update_user,
                    fetch_image,
                    logout_view,
                    )

urlpatterns = [
    path('patients/', PatientProfileListCreateView.as_view(),
         name='patient-list-create'),
    path('dentists/', DentistProfileListCreateView.as_view(),
         name='dentist-list-create'),
    path('update-geocode/', update_geocode, name='update-geocode'),
    path('create/', create_user_from_form, name='create-user-from-form'),
    path('register/patient_form/', register_patient_form,
         name='register-patient-form'),
    path('register/patient/', register_patient, name='register-patient'),
    path('register/dentist/', register_dentist, name='register-dentist'),
    path('register/technician/', register_technician, name='register-technician'),
    path('customlogin/', FormLoginView.as_view(), name='custom-login'),
    path('login/', login_user, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/patient/', patient_dashboard, name='patient_dashboard'),
    path('current_user/', CurrentUserProfileView.as_view(), name='current_user'),
    path('update_current_user/', update_user, name='update_user'),
    path('dashboard/dentist/', dentist_dashboard, name='dentist_dashboard'),
    path('upload-image/', upload_image, name='upload_image'),
    path('fetch-image/', fetch_image, name='fetch_image'),
]

dental_clinic/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .validators import validate_national_id, validate_phone_number


# Create your models here.
class User(AbstractUser):
    is_patient = models.BooleanField(default=False)
    is_dentist = models.BooleanField(default=False)
    is_technician = models.BooleanField(default=False)
    user_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30, null=False, blank=False)
    last_name = models.CharField(max_length=30, null=False, blank=False)
    username = models.CharField(max_length=30, null=False, blank=False, unique=True)
    password = models.CharField(max_length=128, null=False, blank=False)
    address = models.TextField()
    province = models.CharField(max_length=50, null=False, blank=False, default='تهران')
    city = models.CharField(max_length=50, null=False, blank=False, default='تهران')
    phone_number = models.CharField(max_length=15, validators=[validate_phone_number])
    location_latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    location_longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name}, {self.last_name}"


class PatientProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    national_id = models.CharField(max_length=20, validators=[validate_national_id], null=False, blank=False,
                                   default='0000000000')
    # set default value for birth_date
    birth_date = models.DateField(default='2000-01-01', null=False, blank=False)


class DentistProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    speciality = models.CharField(max_length=50, default="General Dentist")
    medical_council_number = models.CharField(max_length=50)
    email = models.EmailField(unique=True)


class TechnicianProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    certification_number = models.CharField(max_length=50)
    email = models.EmailField(unique=True)


class RadiologyImage(models.Model):
    image_id = models.AutoField(primary_key=True)
    user_id = models.CharField(max_length=30, null=False, blank=False, default='00000')
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE, related_name='radiology_images')
    image = models.ImageField(upload_to='radiology_images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    # technician = models.ForeignKey(TechnicianProfile, on_delete=models.CASCADE, limit_choices_to={'is_technician': True})

dental_clinic/users/views.py
import json
from copy import deepcopy

from django.http import JsonResponse, HttpResponseForbidden, Http404, FileResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics, status, permissions
from rest_framework.authtoken.models import Token
from rest_framework.permissions import AllowAny
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes, renderer_classes
from django.conf import settings
from rest_framework.views import APIView
from .models import User, PatientProfile, DentistProfile, TechnicianProfile, RadiologyImage
from .serializers import UserSerializer, PatientProfileSerializer, DentistProfileSerializer
from dental_clinic.utils import get_geocode
from .forms import (PatientRegistrationForm,
                    DentistRegistrationForm,
                    UserRegistrationForm,
                    TechnicianRegistrationForm,
                    RadiologyImageForm,
                    CustomLoginForm)
from .validators import *
from django.contrib.auth.views import LoginView

from datetime import datetime


# Create your views here.


class PatientProfileListCreateView(generics.ListCreateAPIView):
    queryset = PatientProfile.objects.all()
    serializer_class = PatientProfileSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            data = serializer.validated_data['user']
            print(data)
            password = data.get('password')
            password_repeat = serializer.validated_data.get('password_repeat')
            validate_password(password, password_repeat)

            user = User.objects.create(
                username=data.get('username', ''),
                first_name=data.get('first_name', ''),
                last_name=data.get('last_name', ''),
                address=data.get('address', ''),
                province=data.get('province', 'تهران'),
                city=data.get('city', 'تهران'),
                phone_number=data.get('phone_number', '+989000000000'),
                is_patient=True,
                is_dentist=False
            )

            user.set_password(password)
            user.save()

            PatientProfile.objects.create(
                user=user,
                national_id=data.get('national_id', '6816545087'),
                birth_date=data.get('birth_date', timezone.now().date())
            )

            if user.address:
                try:
                    latitude, longitude = get_geocode(
                        user.address, settings.NESHAN_API_KEY)
                    user.location_latitude = latitude
                    user.location_longitude = longitude
                    user.save()
                except ValueError as e:
                    messages.error(request, str(e))
                    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

            messages.success(request, 'Patient registered successfully!')
            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DentistProfileListCreateView(generics.ListCreateAPIView):
    queryset = DentistProfile.objects.all()
    serializer_class = DentistProfileSerializer


CURRENT_USER = {'user': User(), 'is_logged_in': False}


@api_view(['POST'])
def update_geocode(request):
    user = request.user
    address = request.data.get('address')

    if not address:
        return Response({'error': 'Address is required'}, status=status.HTTP_400_BAD_REQUEST)

    try:
        latitude, longitude = get_geocode(address, settings.NESHAN_API_KEY)
        user.latitude = latitude
        user.longitude = longitude
        user.save()
        return Response(UserSerializer(user).data, status=status.HTTP_200_OK)
    except ValueError as e:
        return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
def create_user_from_form(request):
    data = request.data

    print("\n=============================================")
    print(data)
    print("=============================================\n")

    password = data.get('password')
    password_repeat = data.get('password_repeat')
    try:
        validate_password(password, password_repeat)
    except ValidationError as e:
        return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)

    user = User.objects.create(
        first_name=data['first_name'],
        last_name=data['last_name'],
        username=data['username'],
        province=data['province'],
        city=data['city'],
        address=data['address'],
        phone_number=data['phone_number'],
        is_patient=data['is_patient'],
    )

    user.set_password(password)

    if user.is_patient:
        birth_date = data['birth_date']
        birth_date = birth_date.split('T')[0]
        PatientProfile.objects.create(
            user=user, national_id=data['national_id'], birth_date=birth_date)

    if user.is_dentist:
        DentistProfile.objects.create(user=user, phone_number=data['phone_number'],
                                      medical_council_number=data['medical_council_number'])

    # print the user
    print(f"User created: {user}")

    if user.address:
        try:
            latitude, longitude = get_geocode(
                user.address, settings.NESHAN_API_KEY)
            user.latitude = latitude
            user.longitude = longitude
            user.save()
        except ValueError as e:
            return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)

    return Response(UserSerializer(user).data, status=status.HTTP_201_CREATED)


@csrf_exempt
def register_patient_form(request):
    if request.method == 'POST':
        form = PatientRegistrationForm(request.POST)
        print(form)
        if form.is_valid():
            print(
                "0000000000000alsnnaosk[dakmsnljdka[okdfnqpewkv'n;'ewprqfjn;qewrf'")
            data = form.cleaned_data
            print("==================")
            print(data)
            print("==================")
            password = data.get('password')
            password_repeat = data.get('password_repeat')
            try:
                validate_password(password, password_repeat)
            except ValidationError as e:
                form.add_error('password', e)
                return render(request, 'register_patient.html', {'form': form})

            user = User.objects.create(
                username=data.get('username', ''),
                first_name=data.get('first_name', ''),
                last_name=data.get('last_name', ''),
                address=data.get('address', ''),
                province=data.get('province', 'تهران'),
                city=data.get('city', 'تهران'),
                phone_number=data.get('phone_number', '+989000000000'),
                is_patient=True,
                is_dentist=False
            )

            user.set_password(password)
            user.save()

            PatientProfile.objects.create(
                user=user,
                national_id=data.get('national_id', '6816545087'),
                birth_date=data.get('birth_date', timezone.now().date())
            )

            if user.address:
                try:
                    latitude, longitude = get_geocode(
                        user.address, settings.NESHAN_API_KEY)
                    user.location_latitude = latitude
                    user.location_longitude = longitude
                    user.save()
                except ValueError as e:
                    messages.error(request, str(e))
                    return render(request, 'register_patient.html', {'form': form})

            messages.success(request, 'Patient registered successfully!')
            return redirect('register-patient')
    else:
        form = PatientRegistrationForm()
    return render(request, 'register_patient.html', {'form': form})


@csrf_exempt
@api_view(('POST',))
@renderer_classes((TemplateHTMLRenderer, JSONRenderer))
def register_patient(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            password = data.get('password')
            password_repeat = data.get('password_repeat')
            try:
                validate_password(password, password_repeat)
            except ValidationError as e:
                print(e)
                return

            user = User.objects.create(
                username=data.get('username', ''),
                first_name=data.get('first_name', ''),
                last_name=data.get('last_name', ''),
                address=data.get('address', ''),
                province=data.get('province', 'تهران'),
                city=data.get('city', 'تهران'),
                phone_number=data.get('phone_number', '+989000000000'),
                is_patient=True,
                is_dentist=False,
                is_technician=False
            )

            user.set_password(password)
            user.save()

            PatientProfile.objects.create(
                user=user,
                national_id=data.get('national_id', '6816545087'),
                birth_date=data.get('birth_date', timezone.now().date())
            )

dental_clinic/users/templates/base_user.html
{% extends 'base.html' %}

dental_clinic/users/templates/login.html
{% extends 'base_user.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <i class="fas fa-sign-in-alt"></i> Login
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        {{ form.username }}
                        {% if form.username.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.username.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        {{ form.password }}
                        {% if form.password.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.password.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    {% if form.non_field_errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.non_field_errors.0 }}
                    </div>
                    {% endif %}
                    <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-sign-in-alt"></i> Login
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dental_clinic/users/templates/register_dentist.html
{% extends 'base_user.html' %}

{% block title %}Register Dentist{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <i class="fas fa-user-md"></i> Register Dentist
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-user-check"></i> Register
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dental_clinic/users/templates/register_patient.html
{% extends 'base_user.html' %}

{% block title %}Register Patient{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <i class="fas fa-user-plus"></i> Register Patient
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-user-check"></i> Register</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dental_clinic/users/templates/register_technician.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Technician</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h2 class="mt-5">Register as a Technician</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="id_email">Email</label>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label for="id_password1">Password</label>
            {{ form.password1 }}
        </div>
        <div class="form-group">
            <label for="id_password2">Confirm Password</label>
            {{ form.password2 }}
        </div>
        <div class="form-group">
            <label for="id_certification_number">Certification Number</label>
            {{ form.certification_number }}
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

<!-- Include Bootstrap JS and dependencies (Optional) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>